version: "3"

services:
  app:
    container_name: tdm_backend-api
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    tty: true
    volumes:
      - .:/app