# Generated by Django 5.1.2 on 2025-01-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
