# Generated by Django 5.1.2 on 2025-01-09 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appimage',
            old_name='image_url',
            new_name='url',
        ),
    ]
