# Generated by Django 5.1.2 on 2025-01-10 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdm', '0002_rename_image_url_appimage_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryperson',
            name='restaurant',
        ),
    ]
