# Generated by Django 5.1.2 on 2025-01-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdm', '0005_alter_appimage_id_alter_category_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
