# Generated by Django 5.1.2 on 2025-01-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdm', '0006_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appimage',
            name='url',
            field=models.TextField(),
        ),
    ]
