# Generated by Django 5.1.2 on 2025-01-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdm', '0007_alter_appimage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appimage',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
